# Generated by Django 3.1 on 2021-05-23 06:05

from django.db import migrations, models
import django.db.models.deletion
import notepadDB.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('password', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, db_column='parent', null=True, on_delete=django.db.models.deletion.CASCADE, to='notepadDB.folder')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('password', models.UUIDField(default=uuid.uuid4)),
                ('title', models.CharField(max_length=255)),
                ('contents', models.FileField(blank=True, upload_to=notepadDB.models.file_path)),
                ('parent', models.ForeignKey(blank=True, db_column='parent', null=True, on_delete=django.db.models.deletion.CASCADE, to='notepadDB.folder')),
            ],
        ),
    ]
