# Generated by Django 3.1 on 2021-05-23 12:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notepadDB', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='password',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='password',
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='folder',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
