# Generated by Django 3.1 on 2021-05-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notepadDB', '0003_auto_20210523_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='editing',
            field=models.BooleanField(default=False),
        ),
    ]
