# Generated by Django 3.1 on 2021-05-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notepadDB', '0005_remove_file_editing'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='group_size',
            field=models.IntegerField(default=0),
        ),
    ]
