# Generated by Django 3.1 on 2021-05-26 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notepadDB', '0006_file_group_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='group_size',
        ),
    ]
